#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{list_weaver_bundles} = {
    v => 1.1,
    summary => 'List installed Pod::Weaver plugin bundles',
    args => {
    },
};
sub list_weaver_bundles {
    require Module::List;
    my %args = @_;
    my $res = Module::List::list_modules("Pod::Weaver::PluginBundle::",
                                         {list_modules=>1, recurse=>1});
    [200, "OK", [map {s/^Pod::Weaver::PluginBundle:://;$_} sort keys %$res]];
}

Perinci::CmdLine::Any->new(
    url => '/main/list_weaver_bundles',
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

 % list-weaver-bundles

=cut
